const DATA={process:'data/process-model.json',guide:'data/guide-model.json',ai:'data/ai-process-model.json',raw:'data/raw-session.json'};
const state={process:null,guide:null,ai:null,raw:null,selected:0,edits:new Map(),view:'home'};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function load(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`Could not load ${path}`);return r.json()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2400)}
function source(id){return state.process?.steps?.find(s=>s.stepId===id)||null}
function action(s){return String(s?.action||'STEP').toUpperCase()}
function screen(s){return s?.screen?.page||s?.screen?.title||state.process?.applicationName||'Captured evidence'}
function captureParam(){return new URLSearchParams(location.search).get('capture')}
function requestedView(){const p=new URLSearchParams(location.search).get('view');return ['home','guides','tests','knowledge','analytics','settings'].includes(p)?p:null}
function viewName(v){return ({home:'Home',guides:'Guides',tests:'Test Cases',knowledge:'Knowledge',analytics:'Analytics',settings:'Settings'})[v]||'Home'}
function initSummary(){const p=state.process,a=state.ai.process||{},g=state.guide.steps?.length||0,t=a.businessSteps?.length||0,c=state.ai.coverage?.coveragePercent??100;
  $('#metricCoverage').textContent=`${c}%`;$('#metricRecorded').textContent=p.steps?.length||0;$('#metricTest').textContent=`${t} execution steps`;$('#orbitGuide').textContent=`${g} steps`;$('#orbitTest').textContent=`${t} steps`;
  $('#homeTitle').textContent=a.name||p.name||'Latest capture';$('#homeDesc').textContent=a.description||p.description||'Reviewed process capture';$('#homeApp').textContent=p.applicationName||a.application||'Web application';$('#homeCapture').textContent=p.captureId||'CAP-…';$('#guideCount').textContent=g;$('#testCount').textContent=t;
  $('#guideTitlePage').textContent=a.name||p.name||'Process Guide';$('#guideSubtitle').textContent=`AI-enhanced wording across ${g} reviewed steps. Sequence and evidence remain source-controlled.`;$('#stepsCount').textContent=`${g} steps`;
  $('#aiContextTitle').textContent=a.name||p.name||'Latest capture';$('#aiContextMeta').textContent=`${p.steps?.length||0} recorder steps · ${t} test steps`;
  const cp=captureParam();if(cp&&cp!==p.captureId)toast(`Preview uses ${p.captureId}; live capture loading connects next.`)
}
function activate(v,update=true){if(!['home','guides','tests','knowledge','analytics','settings'].includes(v))v='home';state.view=v;$$('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===v));$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#crumb').textContent=viewName(v);$('#topContext').textContent=v==='home'?'Your process intelligence workspace':(state.ai.process?.name||state.process.name||state.process.captureId);renderSuggestions(v);if(update){const u=new URL(location.href);u.searchParams.set('view',v);history.replaceState(null,'',u)} }
function renderSuggestions(v){const map={home:['Summarize this process','What did Krivyo generate?','Which outputs are ready?'],guides:['Improve this step wording','Show the original recorder wording','Which guide steps contain test data?'],tests:['Which expected results are inferred?','Show the test data used','Which test steps group multiple source steps?'],knowledge:['How will this become process knowledge?','What related processes could connect here?','Explain source traceability'],analytics:['Find manual-data hotspots','Which steps repeat most?','Find automation candidates'],settings:['What data is stored in cloud?','Are screenshots uploaded?','Explain AI provenance']};$('#suggestions').innerHTML=(map[v]||map.home).map(x=>`<button data-prompt="${esc(x)}">${esc(x)}</button>`).join('');wirePromptButtons()}
function guideData(){const s=state.guide.steps[state.selected],e=state.edits.get(s.sourceStepId);return e?{...s,...e}:s}
function renderSteps(filter=''){const list=$('#stepList');list.innerHTML='';const f=filter.trim().toLowerCase();state.guide.steps.forEach((s,i)=>{const src=source(s.sourceStepId),title=state.edits.get(s.sourceStepId)?.title||s.title;if(f&&!`${title} ${s.description} ${action(src)}`.toLowerCase().includes(f))return;const b=document.createElement('button');b.className=`step-btn${i===state.selected?' active':''}`;b.innerHTML=`<span class="step-index">${String(s.sequence).padStart(2,'0')}</span><span><strong>${esc(title)}</strong><small>${esc(action(src))}</small></span>`;b.onclick=()=>{state.selected=i;renderSteps($('#stepSearch').value);renderGuide()};list.appendChild(b)})}
function renderGuide(){const s=guideData();if(!s)return;const src=source(s.sourceStepId),total=state.guide.steps.length;$('#stepLabel').textContent=`STEP ${String(s.sequence).padStart(2,'0')} OF ${String(total).padStart(2,'0')}`;$('#stepNo').textContent=String(s.sequence).padStart(2,'0');$('#guideStepTitle').textContent=s.title;$('#guideStepDesc').textContent=s.description;$('#actionBadge').textContent=action(src);$('#screenContext').textContent=`${state.process.applicationName||'Application'} · ${screen(src)}`;$('#sourceId').textContent=s.sourceStepId;$('#confidence').textContent=`${Math.round((s.confidence??1)*100)}% confidence`;$('#editStep').textContent='Edit wording';$('#guideStepTitle').contentEditable='false';$('#guideStepDesc').contentEditable='false'}
function wireGuide(){ $('#editStep').onclick=()=>{const t=$('#guideStepTitle'),d=$('#guideStepDesc'),editing=t.contentEditable==='true';if(!editing){t.contentEditable='true';d.contentEditable='true';$('#editStep').textContent='Save wording';t.focus();return}const s=state.guide.steps[state.selected];state.edits.set(s.sourceStepId,{title:t.textContent.trim(),description:d.textContent.trim()});t.contentEditable='false';d.contentEditable='false';$('#editStep').textContent='Edit wording';renderSteps($('#stepSearch').value);toast('Guide wording updated locally')};
  $('#restoreStep').onclick=()=>{const s=state.guide.steps[state.selected];state.edits.delete(s.sourceStepId);renderGuide();renderSteps($('#stepSearch').value);toast('Restored AI wording')};$('#restoreAll').onclick=()=>{state.edits.clear();renderSteps($('#stepSearch').value);renderGuide();toast('All local edits restored')};$('#stepSearch').oninput=e=>renderSteps(e.target.value)}
function testDataFor(step){const ids=new Set(step.sourceStepIds||[]);return (state.ai.process?.testData||[]).filter(x=>(x.sourceStepIds||[]).some(id=>ids.has(id)))}
function renderTest(){const p=state.ai.process||{};$('#testTitle').textContent=p.name||'Generated Test Case';$('#testObjective').textContent=p.businessObjective||'—';$('#testApp').textContent=p.application||'—';$('#testModule').textContent=p.module||'—';$('#testArea').textContent=p.businessArea||'—';$('#testCoverage').textContent=`${state.ai.coverage?.coveragePercent??100}%`;const pre=p.preconditions?.[0];$('#precondition').textContent=pre?.text||'No explicit precondition generated.';$('#preConfidence').textContent=pre?`${Math.round((pre.confidence??0)*100)}% confidence`:'—';const body=$('#testBody');body.innerHTML='';(p.businessSteps||[]).forEach(s=>{const data=testDataFor(s),basis=String(s.expectedResultBasis||'UNKNOWN').toLowerCase(),n=s.sourceStepIds?.length||0,tr=document.createElement('tr');tr.innerHTML=`<td>${s.sequence}</td><td><span class="t-title">${esc(s.title)}</span><span class="t-inst">${esc(s.instruction)}</span></td><td>${data.length?data.map(d=>`<span class="data-chip">${esc(d.field)}: ${esc(d.value)}</span>`).join(''):'<span class="t-inst">—</span>'}</td><td>${esc(s.expectedResult||'To be verified during execution.')}<br><span class="basis ${basis}">${esc(s.expectedResultBasis||'Unknown')}</span></td><td><span class="source-link">${n} source step${n===1?'':'s'}</span></td><td><span class="score">${Math.round((s.confidence??0)*100)}%</span></td>`;body.appendChild(tr)})}
function renderDetails(){const p=state.process,a=state.ai,g=state.guide,rows1=[['Capture ID',p.captureId],['Process ID',p.processId],['Application',p.applicationName],['Processing version',p.processingVersion],['Recorded steps',p.steps?.length],['Raw events',state.raw.events?.length??'Preserved']],rows2=[['Guide model',g.ai?.model],['Guide prompt',g.ai?.promptVersion],['Process model',a.ai?.model],['Process prompt',a.ai?.promptVersion],['Guide coverage',`${g.coverage?.coveragePercent??0}%`],['Process coverage',`${a.coverage?.coveragePercent??0}%`]];const draw=(id,rows)=>$(id).innerHTML=rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v??'—')}</dd></div>`).join('');draw('#captureDetails',rows1);draw('#aiDetails',rows2)}
function exportCsv(){const rows=[['Sequence','Title','Instruction','Test Data','Expected Result','Basis','Source Step IDs','Confidence']];for(const s of state.ai.process?.businessSteps||[]){rows.push([s.sequence,s.title,s.instruction,testDataFor(s).map(d=>`${d.field}=${d.value}`).join(' | '),s.expectedResult||'To be verified during execution',s.expectedResultBasis,(s.sourceStepIds||[]).join(' | '),Math.round((s.confidence||0)*100)+'%'])}const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${state.process.captureId||'krivyo'}-test-script.csv`;a.click();URL.revokeObjectURL(url);toast('Test script CSV exported')}
function wireNav(){$$('[data-view]').forEach(b=>b.onclick=()=>activate(b.dataset.view));$$('[data-open]').forEach(b=>b.onclick=()=>activate(b.dataset.open));$('#collapseNav').onclick=()=>document.body.classList.toggle('nav-collapsed');$('#collapseAi').onclick=()=>document.body.classList.toggle('ai-collapsed')}
function wirePalette(){const p=$('#palette'),open=()=>{p.classList.add('open');$('#commandSearch').focus()},close=()=>p.classList.remove('open');$('#commandButton').onclick=open;$('.palette-bg').onclick=close;$$('[data-command]').forEach(b=>b.onclick=()=>{activate(b.dataset.command);close()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}if(e.key==='Escape')close()})}
function wirePromptButtons(){$$('[data-prompt]',$('#suggestions')).forEach(b=>b.onclick=()=>{$('#aiInput').value=b.dataset.prompt;$('#aiInput').focus()})}
function wireAi(){wirePromptButtons();$('#composer').onsubmit=e=>{e.preventDefault();const text=$('#aiInput').value.trim();if(!text)return;const msg=document.createElement('div');msg.className='message';msg.innerHTML=`<span class="msg-orb" style="background:#EAF3F1;color:#1A4B44">A</span><div><p>${esc(text)}</p></div>`;$('#conversation').appendChild(msg);$('#aiInput').value='';toast('Secure workspace AI chat connects in the next backend step')}}
function wireMisc(){$('#exportCsv').onclick=exportCsv;$('#downloadPdf').onclick=()=>toast('Enhanced PDF connection comes after live workspace data');$('#runTest').onclick=()=>toast('UAT execution is the next Test Cases milestone');$('#newCapture').onclick=()=>toast('The Chrome extension remains the capture entry point')}
async function init(){try{[state.process,state.guide,state.ai,state.raw]=await Promise.all([load(DATA.process),load(DATA.guide),load(DATA.ai),load(DATA.raw)]);initSummary();renderSteps();renderGuide();renderTest();renderDetails();wireGuide();wireNav();wirePalette();wireAi();wireMisc();activate(requestedView()||(captureParam()?'guides':'home'),false)}catch(err){console.error(err);$('#main').innerHTML=`<div style="padding:40px"><h1>Krivyo Workspace</h1><p>Could not load workspace preview data.</p><pre>${esc(err.message)}</pre></div>`}}
document.addEventListener('DOMContentLoaded',init);
